name: started_workflow
on: 
  push:
    branches: main
jobs:
  real_data:
     runs-on: ubuntu-latest
     steps:
       - name: check_actions
         uses: actions/checkout@v4
       - name: check all files which inserted in project
         run:  ls
       - name: check html files
         run: test -f index.html
       - name: check css files
         run: test -f style.css
       - name: run_msg_test
         run: echo "workflow_created"
